sources:
  - name: graphile
    handler:
      postgraphile:
        connectionString: postgres://demo:demo@localhost:5433/demo
        cacheIntrospection: true
        appendPlugins:
          - "postgraphile-plugin-connection-filter"
    transforms:
      - prefix:
          value: DB_
      - namingConvention:
          fieldNames: snakeCase
  - name: rest
    handler:
        openapi:
          source: https://petstore.swagger.io/v2/swagger.json
    transforms:
      - prefix:
          value: REST_
      - namingConvention:
          fieldNames: snakeCase 
additionalTypeDefs: |
      type Test{
        name: String
      }
      extend type Query {
        cities(filter: DB_CityFilter): DB_CitiesConnection
      }

additionalResolvers:
  - ./add-resolvers.js